## Handling missing values using different techniques

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

i have just gave the path of the dataset extracted from the public data

In [2]:
df = pd.read_csv("C:/Users/sathv/Downloads/Churn_model.csv")

extract information of the dataset

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Firstname        9993 non-null   object
 3   Lastname         9994 non-null   object
 4   CreditScore      10000 non-null  int64
 5   Geography        10000 non-null  object
 6   Gender           9892 non-null   object
 7   Age              9400 non-null   float64
 8   Tenure           10000 non-null  int64
 9   Balance          10000 non-null  float64
 10  NumOfProducts    10000 non-null  int64
 11  HasCrCard        10000 non-null  int64
 12  IsActiveMember   10000 non-null  int64
 13  EstimatedSalary  10000 non-null  float64
 14  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(4)
memory usage: 1.1+ MB

here the dataset consists of non null values that means there are no null values and we have around 10000 records and 14 columns out of it.
missing values:-
7-firstname; 6-lastname; 108-gender; 600-Age

till now i have done finding missing values in manual way lets do it with coding.

In [4]:
print(df.isnull().sum())

RowNumber            0
CustomerId           0
Firstname            7
Lastname             6
CreditScore          0
Geography            0
Gender             108
Age                600
Tenure               0
Balance              0
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary      0
Exited               0
dtype: int64

Handling missing values: 
1. Deleting the columns with missing values.
(the problem with this method is that we may lose valuable information on that feature, as we have deleted it completely due to some null values)
2. Delecting the rows with the missing values.(in this case there are possibiliies of getting better accuracy than before.this might be because the columns contains more valuable information than we expected)

3. Imputation method: filling the missing data with the mean or median value if its a numerical variable.
4. filling the missing data with mode if its a categorical value.
5. filling the numerical value with 0 or -999 or some other number that will not occur in the data,this can be done so that the machine can recognise that the data is not real or is different.
6. filling the categorical value with a new type for the missing values.

In [5]:
#deleting the columns with missing values
updated_df1 = df.dropna(axis=1)
updated_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  object
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), object(1)
memory usage: 859.5+ KB

here the null values containing columns are all deleted as of our data the firstname and lastname of that data are important columns so it is not a best way of handling missing values.

In [6]:
#deleting the rows with the missing values
updated_df2 = df.dropna(axis=0)
updated_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9337 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        9337 non-null   int64
 1   CustomerId       9337 non-null   int64
 2   Firstname        9337 non-null   object
 3   Lastname         9337 non-null   object
 4   CreditScore      9337 non-null   int64
 5   Geography        9337 non-null   object
 6   Gender           9337 non-null   object
 7   Age              9337 non-null   float64
 8   Tenure           9337 non-null   int64
 9   Balance          9337 non-null   float64
 10  NumOfProducts    9337 non-null   int64
 11  HasCrCard        9337 non-null   int64
 12  IsActiveMember   9337 non-null   int64
 13  EstimatedSalary  9337 non-null   float64
 14  Exited           9337 non-null   int64
dtypes: float64(3), int64(8), object(4)
memory usage: 1.1+ MB

in this we have all the columns and the rows which has the null values have been deleted.

In [7]:
updated_df1  = df
#as we have categorical data Firstname and lastname we will fill the missing values with unknown
updated_df1['Firstname'] = updated_df1['Firstname'].fillna("unknown")
updated_df1['Lastname'] = updated_df1['Lastname'].fillna("unknown")
updated_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Firstname        10000 non-null  object
 3   Lastname         10000 non-null  object
 4   CreditScore      10000 non-null  int64
 5   Geography        10000 non-null  object
 6   Gender           9892 non-null   object
 7   Age              9400 non-null   float64
 8   Tenure           10000 non-null  int64
 9   Balance          10000 non-null  float64
 10  NumOfProducts    10000 non-null  int64
 11  HasCrCard        10000 non-null  int64
 12  IsActiveMember   10000 non-null  int64
 13  EstimatedSalary  10000 non-null  float64
 14  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(4)
memory usage: 1.1+ MB

In [8]:
#handling missing values of age(with mean)
#filling the missing values with mean as the data is numerical and the mean is not affected by outliers.
df['Age'].mean()
updated_df1['Age'] = updated_df1['Age'].fillna(df['Age'].mean())

In [9]:
updated_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Firstname        10000 non-null  object
 3   Lastname         10000 non-null  object
 4   CreditScore      10000 non-null  int64
 5   Geography        10000 non-null  object
 6   Gender           9892 non-null   object
 7   Age              10000 non-null  float64
 8   Tenure           10000 non-null  int64
 9   Balance          10000 non-null  float64
 10  NumOfProducts    10000 non-null  int64
 11  HasCrCard        10000 non-null  int64
 12  IsActiveMember   10000 non-null  int64
 13  EstimatedSalary  10000 non-null  float64
 14  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(4)
memory usage: 1.1+ MB

In [10]:
#df['Age'].median()
#updated_df1['Age'] = updated_df1['Age'].fillna(df['Age'].median())

In [11]:
updated_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Firstname        10000 non-null  object
 3   Lastname         10000 non-null  object
 4   CreditScore      10000 non-null  int64
 5   Geography        10000 non-null  object
 6   Gender           9892 non-null   object
 7   Age              10000 non-null  float64
 8   Tenure           10000 non-null  int64
 9   Balance          10000 non-null  float64
 10  NumOfProducts    10000 non-null  int64
 11  HasCrCard        10000 non-null  int64
 12  IsActiveMember   10000 non-null  int64
 13  EstimatedSalary  10000 non-null  float64
 14  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(4)
memory usage: 1.1+ MB

lets fill the null values for gender too using backward and forward filling method

In [12]:
#backward filling method
updated_df1['Gender'] = updated_df1['Gender'].bfill()

In [13]:
updated_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Firstname        10000 non-null  object
 3   Lastname         10000 non-null  object
 4   CreditScore      10000 non-null  int64
 5   Geography        10000 non-null  object
 6   Gender           10000 non-null  object
 7   Age              10000 non-null  float64
 8   Tenure           10000 non-null  int64
 9   Balance          10000 non-null  float64
 10  NumOfProducts    10000 non-null  int64
 11  HasCrCard        10000 non-null  int64
 12  IsActiveMember   10000 non-null  int64
 13  EstimatedSalary  10000 non-null  float64
 14  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(4)
memory usage: 1.1+ MB

In [14]:
#updated_df1['Gender'] = updated_df1['Gender'].ffill()
#updated_df1.info()

foe now we have handled all the missing values of firstname,lastname,Age, Gender now we have all the records.

## Feature Scaling of the data

to perform feature scaling we require sklearn as default we already have scikit-learn

In [15]:
updated_df1.head()

,RowNumber,CustomerId,Firstname,Lastname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Grace,Williams,619,France,Female,42.000000,2,0.00,1,1,1,101348.88,1
1,2,15647311,David,Jones,608,Spain,Female,41.000000,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Hank,Williams,502,France,Female,42.000000,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Eva,Taylor,699,France,Female,38.912128,1,0.00,2,0,0,93826.63,0
4,5,15737888,Grace,Miller,850,Spain,Female,43.000000,2,125510.82,1,1,1,79084.10,0

import minmax scaler - normalization technique and standard scaler -standardization technique

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

Normalization - it is a scaling technique in which values are shifted and rescaled so that they end up ranging between 0 and 1 it is also known as Min-Max Scaling.
Standardization - Standardization is another scaling technique where the values are centered around the mean with a unit standard deviation.this means that the mean of the attribute becomes zero and the resultant distribution has a unit standard deviation.

In [18]:
updated_df1.describe().round(2)

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.0
mean,5000.50,15690940.57,650.53,38.91,5.01,76485.89,1.53,0.71,0.52,100090.24,0.2
std,2886.90,71936.19,96.65,10.19,2.89,62397.41,0.58,0.46,0.50,57510.49,0.4
min,1.00,15565701.00,350.00,18.00,0.00,0.00,1.00,0.00,0.00,11.58,0.0
25%,2500.75,15628528.25,584.00,32.00,3.00,0.00,1.00,0.00,0.00,51002.11,0.0
50%,5000.50,15690738.00,652.00,38.00,5.00,97198.54,1.00,1.00,1.00,100193.92,0.0
75%,7500.25,15753233.75,718.00,43.00,7.00,127644.24,2.00,1.00,1.00,149388.25,0.0
max,10000.00,15815690.00,850.00,92.00,10.00,250898.09,4.00,1.00,1.00,199992.48,1.0

In [19]:
updated_df1.head(10).round(2)

,RowNumber,CustomerId,Firstname,Lastname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Grace,Williams,619,France,Female,42.00,2,0.00,1,1,1,101348.88,1
1,2,15647311,David,Jones,608,Spain,Female,41.00,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Hank,Williams,502,France,Female,42.00,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Eva,Taylor,699,France,Female,38.91,1,0.00,2,0,0,93826.63,0
4,5,15737888,Grace,Miller,850,Spain,Female,43.00,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Jack,Smith,645,Spain,Male,44.00,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Carol,Wilson,822,France,Male,50.00,7,0.00,2,1,1,10062.80,0
7,8,15656148,Grace,Wilson,376,Germany,Female,29.00,4,115046.74,4,1,0,119346.88,1
8,9,15792365,Hank,Jones,501,France,Male,44.00,4,142051.07,2,0,1,74940.50,0
9,10,15592389,Eva,Wilson,684,France,Male,27.00,2,134603.88,1,1,1,71725.73,0

lets perform normalization for Age and Tenure
Person Age and tenure is how many years is the person do it (timespan)

In [22]:
new_df = pd.DataFrame(df,columns=['Age','Tenure'])

In [23]:
new_df.head(10)

         Age  Tenure
0  42.000000       2
1  41.000000       1
2  42.000000       8
3  38.912128       1
4  43.000000       2
5  44.000000       8
6  50.000000       7
7  29.000000       4
8  44.000000       4
9  27.000000       2

In [24]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     10000 non-null  float64
 1   Tenure  10000 non-null  int64
dtypes: float64(1), int64(1)
memory usage: 156.4 KB

In [ ]:
scaler = MinMaxScaler() #initializing the scaler
new_df_sc = scaler.fit_transform(new_df) #normalized

In [26]:
print(new_df_sc)

[[0.32432432 0.2       ]
 [0.31081081 0.1       ]
 [0.32432432 0.8       ]
 ...
 [0.24324324 0.7       ]
 [0.32432432 0.3       ]
 [0.13513514 0.4       ]]

In [ ]:
scaler_1 = StandardScaler() #intializing the scaler
new_df_sc1 = scaler_1.fit_transform(new_df) #standardized

In [28]:
print(new_df_sc1)

[[ 0.30297097 -1.04175968]
 [ 0.20485455 -1.38753759]
 [ 0.30297097  1.03290776]
 ...
 [-0.28572753  0.68712986]
 [ 0.30297097 -0.69598177]
 [-1.07065886 -0.35020386]]

## Outliers treatment

different techniques that we use to identify the outliers in the data

In [31]:
# 3 Sigma Technique
import statistics as stats
data = updated_df1

In [32]:
data.head(10)

,RowNumber,CustomerId,Firstname,Lastname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Grace,Williams,619,France,Female,42.000000,2,0.00,1,1,1,101348.88,1
1,2,15647311,David,Jones,608,Spain,Female,41.000000,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Hank,Williams,502,France,Female,42.000000,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Eva,Taylor,699,France,Female,38.912128,1,0.00,2,0,0,93826.63,0
4,5,15737888,Grace,Miller,850,Spain,Female,43.000000,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Jack,Smith,645,Spain,Male,44.000000,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Carol,Wilson,822,France,Male,50.000000,7,0.00,2,1,1,10062.80,0
7,8,15656148,Grace,Wilson,376,Germany,Female,29.000000,4,115046.74,4,1,0,119346.88,1
8,9,15792365,Hank,Jones,501,France,Male,44.000000,4,142051.07,2,0,1,74940.50,0
9,10,15592389,Eva,Wilson,684,France,Male,27.000000,2,134603.88,1,1,1,71725.73,0

In [33]:
type(data)

pandas.core.frame.DataFrame

here we are creating a function, that function is for the outliers
outliers are also called as anomalies.

In [ ]:
# function to detect outliers
def find_anomalies(data):
    # here find_anomalies is a function name.it takes data as input and returns a list of anomalies.
    #define a list to accumlate anomalies
    anomalies = []
    #set upper and lower limit to 3 sigma
    lower_limit =